#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

cpu_count=$(sysctl -n hw.ncpu)

./build-deps --bootstrap-b2 --configure

echo "using darwin ;" >> project-config.jam

./b2 -j$cpu_count variant=release tests//run
