#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $script_dir/../..

export CC=clang-3.8
export CXX=clang++-3.8
export CXXFLAGS=-stdlib=libc++

cpu_count=$(nproc)

# make b2 available to dependencies once it's bootstrapped
export PATH=$(pwd)/bootstrap:$PATH

./build-deps --bootstrap-b2 --configure

cat << PROJECT_CONFIG >> project-config.jam
using clang : : $CXX :
    <cxxflags>$CXXFLAGS
    <linkflags>$CXXFLAGS
;
PROJECT_CONFIG

./b2 -j$cpu_count tests//run
