#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

export CC=clang-3.8
export CXX=clang++-3.8
export CXXFLAGS=-stdlib=libc++
export LDFLAGS=-lc++

# the benchmarks built with this would NOT be good with coverage
./scripts/build --install --enable-coverage
./tests/dist/okui-tests
