#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

if [[ -z $ANALYSIS ]] ; then
    ./scripts/build --target=appletvos --install
else
    ./scripts/build --target=appletvos --variant=debug --enable-analysis
fi
