#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

$script_dir/build-common

if [[ -z $ANALYSIS ]] ; then
    ./scripts/build --install --enable-coverage
    ./tests/dist/okui-tests
else
    ./scripts/build --variant=debug --enable-analysis
fi
