#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

if [[ ! -d $ANDROID_TOOLCHAIN ]] ; then
    echo "error: android toolchain not present in $ANDROID_TOOLCHAIN"
    exit 1
fi

$script_dir/build-common

./scripts/build --target=android --install
