#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

# the benchmarks built with this would NOT be good with coverage
./scripts/build --install --enable-coverage
./tests/dist/okui-tests
