#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

sysroot=$(xcrun --show-sdk-path --sdk appletvos)
platform_root=$(xcrun --show-sdk-platform-path --sdk appletvos)

cpu_count=$(sysctl -n hw.ncpu)

./build-deps --bootstrap-b2 --configure --needy-target-args="-t tvos"

cat << PROJECT_CONFIG >> project-config.jam
import feature ;
feature.extend target-os : appletv ;
feature.extend instruction-set : arm64 ;
feature.set-default target-os : appletv ;
feature.feature target : appletvos : composite propagated ;
feature.compose <target>appletvos : <architecture>arm <target-os>appletv <instruction-set>arm64 ;

using darwin : appletvos : clang++ :
    <striper> <root>"$platform_root/Developer"
    <compileflags>-fembed-bitcode
    <compileflags>"-isysroot $sysroot"
    <linkflags>"-isysroot $sysroot"
:
    <target>appletvos <architecture>arm <target-os>appletv <instruction-set>arm64
;
PROJECT_CONFIG

./b2 -j$cpu_count variant=release target-os=appletv
