#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $script_dir/../..

if [[ $TRAVIS_EVENT_TYPE == 'cron' ]] ; then
    scripts/live-ci-tools/nightly-checkout.py \
        --needy=needy/scripts/needy \
        scraps
fi
