#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$script_dir/install-common-dependencies

pip install awscli git+https://github.com/bittorrent/simon.git@master#egg=simon
