#!/bin/bash -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$script_dir/install-common-dependencies

sudo apt-get update
sudo apt-get install -y clang-3.8 libc++-dev libc++abi-dev xutils-dev
